### PR TITLE
Add Laravel 9 Support

### PR DESCRIPTION
**Pull request by nbyloff**
add Laravel 9 support

### CODE REVIEW

**Comment by nbyloff** [comment]
closes #54

**Comment by colivinggit** [comment]
Please deploy!

**Comment by colivinggit** [comment]
Please push the update. We need Laravel 9 support.

**Comment by nbyloff** [comment]
@colivinggit The seeders need to be updated for L9 support as well, so this is not completely ready. This is also not a paid package so if you're relying on it being updated quickly, I'd fork it.

**Comment by colivinggit** [comment]
I believe we will fork it and keep it updated ourselves.

Daniel

**Pull request merged**
