### PR TITLE
Added Timestamp to City and Numeric Code to Country. Fixed eloquent modeling on all models. Added two extra static Timezone functions to City

### PR DESCRIPTION
**Pull request by seche**
Bug Fix for Eloquent Models: added code to ignore that created_at and updated_at do not exist on the model.

Added to City Model a function timezoneAbbrev($iana_timezone) to retreive a timezone Abbreviation
Added to City Model a function timezoneOffset($iana_timezone) to retreive the timezone offset.

### CODE REVIEW

**Comment by seche** [comment]
Also working on seeding more data, just not ready to add it to the PR just yet.

**Comment by seche** [comment]
@khsing here you go. 3 different commits with my changes. 

I also created myself a front end for data manipulation to use as a tool for Laravel Nova Admin Panel: https://packagist.org/packages/seche/nova-laravel-world

**Comment by seche** [comment]
Updated Cities Table with cities of 5000+ population from https://download.geonames.org/export/dump/.

**Review by umutphp — APPROVED** [review]
Greate PR to solve multiple problems :). 

Many thanks @seche . I hope It will be accepted by @khsing

**Comment by seche** [comment]
Seems some cities are missing, I will update the data again in the coming days if life permits. Thanks :)

**Comment by seche** [comment]
@khsing  I completed the data import/validation from Geonames. Roughly 200k cities

**Pull request merged**
